export const cuisinesList = [
    "American",
    "Asian",
    "Bakery",
    "Bar Food",
    "BBQ",
    "Beverages",
    "Biryani",
    "Burger",
    "Cafe",
    "Chinese",
    "Desserts",
    "Fast Food",
    "Healthy Food",
    "Ice Cream",
    "Indian",
    "Italian",
    "Japanese",
    "Juices",
    "Kebab",
    "Mexican",
    "Pizza",
    "Salad",
    "Seafood",
    "Street Food",
    "Sushi",
    "Thai",
    "Vegetarian",
    "Vietnamese",
    
]